FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /main ./cmd/api/main.go

FROM alpine:latest

WORKDIR /app

COPY --from=builder /main .

COPY --from=builder /app/scripts ./scripts
COPY --from=builder /app/supabase/config.toml ./config.toml
COPY --from=builder /app/migrations ./migrations

EXPOSE 8080

CMD ["./main"]
